import { prisma } from "../lib/prisma.ts";
import { patterns } from "../app/data/patterns.ts";
import { users } from "../app/data/users.ts";
import { activities } from "../app/data/activities.ts";
import type { UserInterface, ActivityInterface } from "../app/types/user.ts";
import type { PatternInterface } from "../app/types/patterns.ts";

async function main() {
  // 1) Seed users
  for (const u of users as UserInterface[]) {
    await prisma.user.create({
      data: {
        // id is generated by DB (uuid())
        email: u.email,
        handle: u.handle,
        name: u.name,
        location: u.location,
        lastPlayedText: u.lastPlayedText ?? null,
        lastPlayedAt: null,
        streak: u.streak,
        streakMax: u.streakMax,
        scoreValue: u.scoreValue,
        scoreMax: u.scoreMax,
        progressPct: u.progressPct,
        skill: u.skill,
      },
    });
  }

  // 👉 get one real user id to use as a placeholder FK
  const firstUser = await prisma.user.findFirst({ select: { id: true } });
  if (!firstUser) throw new Error("No users inserted; cannot seed activities.");

  // 2) Seed activities (temporary: attach to first user)
  for (const a of activities as ActivityInterface[]) {
    await prisma.activity.create({
      data: {
        userId: firstUser.id,
        type: a.type,
        occurredAt: new Date(a.occurredAt),
        topic: a.topic ?? null,
        durationSeconds:
          a.type === "PRACTICE" ? (a.durationSeconds ?? 0) : null,
        scoreCorrect: a.type === "QUIZ" ? (a.scoreCorrect ?? 0) : null,
        scoreTotal: a.type === "QUIZ" ? (a.scoreTotal ?? 0) : null,
        strikes: a.type === "QUIZ" ? (a.strikes ?? 0) : null,
      },
    });
  }

  // 3) Seed patterns
  for (const p of patterns as PatternInterface[]) {
    await prisma.pattern.upsert({
      where: { name: p.name },
      update: {
        bpm: p.bpm,
        stepLength: p.stepLength,
        difficulty: p.difficulty,
        pattern: p.pattern,
        description: p.description ?? null,
        tags: p.tags ?? [],
      },
      create: {
        name: p.name,
        bpm: p.bpm,
        stepLength: p.stepLength,
        difficulty: p.difficulty,
        pattern: p.pattern,
        description: p.description ?? null,
        tags: p.tags ?? [],
      },
    });
  }

  console.log("✅ Seeding complete");
}

main()
  .catch((e) => {
    console.error("❌ Seed error:", e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
